"""added timestamp fields

Revision ID: 347cbd82ad8a
Revises: 5ec9081d8838
Create Date: 2023-05-26 15:13:30.520440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347cbd82ad8a'
down_revision = '5ec9081d8838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('published_at')

    with op.batch_alter_table('skis', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
