"""added ski and user models

Revision ID: 5ec9081d8838
Revises: 
Create Date: 2023-05-26 10:28:04.458688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec9081d8838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('lengths', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('stoke_profile', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('stoke_profile', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ski_users',
    sa.Column('ski_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ski_id'], ['skis.id'], name=op.f('fk_ski_users_ski_id_skis')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ski_users_user_id_users')),
    sa.PrimaryKeyConstraint('ski_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ski_users')
    op.drop_table('users')
    op.drop_table('skis')
    # ### end Alembic commands ###
